[2024-03-12T13:14:19.861+0000] {processor.py:161} INFO - Started process (PID=34) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:14:19.862+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:14:19.865+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:14:19.865+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:14:19.877+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:14:19.875+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:14:19.877+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:14:19.893+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.042 seconds
[2024-03-12T13:14:50.094+0000] {processor.py:161} INFO - Started process (PID=41) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:14:50.095+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:14:50.097+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:14:50.097+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:14:50.104+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:14:50.103+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:14:50.105+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:14:50.118+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.027 seconds
[2024-03-12T13:15:20.349+0000] {processor.py:161} INFO - Started process (PID=48) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:15:20.350+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:15:20.352+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:15:20.352+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:15:20.361+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:15:20.360+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:15:20.362+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:15:20.381+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.036 seconds
[2024-03-12T13:15:50.771+0000] {processor.py:161} INFO - Started process (PID=55) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:15:50.773+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:15:50.777+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:15:50.777+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:15:50.787+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:15:50.786+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:15:50.788+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:15:50.810+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.048 seconds
[2024-03-12T13:16:21.163+0000] {processor.py:161} INFO - Started process (PID=62) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:16:21.163+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:16:21.165+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:16:21.164+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:16:21.170+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:16:21.169+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:16:21.171+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:16:21.185+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.025 seconds
[2024-03-12T13:16:51.542+0000] {processor.py:161} INFO - Started process (PID=69) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:16:51.544+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:16:51.546+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:16:51.546+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:16:51.556+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:16:51.555+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:16:51.556+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:16:51.578+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.041 seconds
[2024-03-12T13:17:21.899+0000] {processor.py:161} INFO - Started process (PID=76) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:17:21.899+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:17:21.901+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:17:21.901+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:17:21.907+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:17:21.906+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:17:21.907+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:17:21.922+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.026 seconds
[2024-03-12T13:17:52.296+0000] {processor.py:161} INFO - Started process (PID=83) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:17:52.298+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:17:52.299+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:17:52.299+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:17:52.303+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:17:52.303+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:17:52.304+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:17:52.313+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.019 seconds
[2024-03-12T13:18:22.771+0000] {processor.py:161} INFO - Started process (PID=90) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:18:22.773+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:18:22.777+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:18:22.777+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:18:22.786+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:18:22.785+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:18:22.787+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:18:22.807+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.041 seconds
[2024-03-12T13:18:53.154+0000] {processor.py:161} INFO - Started process (PID=97) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:18:53.155+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:18:53.157+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:18:53.157+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:18:53.163+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:18:53.162+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:18:53.164+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:18:53.177+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.029 seconds
[2024-03-12T13:19:23.543+0000] {processor.py:161} INFO - Started process (PID=104) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:19:23.544+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:19:23.545+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:19:23.545+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:19:23.550+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:19:23.549+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:19:23.550+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:19:23.561+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.020 seconds
[2024-03-12T13:19:53.857+0000] {processor.py:161} INFO - Started process (PID=111) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:19:53.858+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:19:53.859+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:19:53.859+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:19:53.864+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:19:53.864+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:19:53.865+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:19:53.884+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.029 seconds
[2024-03-12T13:20:24.285+0000] {processor.py:161} INFO - Started process (PID=118) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:20:24.286+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:20:24.291+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:20:24.290+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:20:24.300+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:20:24.299+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:20:24.301+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:20:24.323+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.045 seconds
[2024-03-12T13:20:54.629+0000] {processor.py:161} INFO - Started process (PID=125) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:20:54.630+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:20:54.633+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:20:54.633+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:20:54.642+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:20:54.641+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:20:54.643+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:20:54.666+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.043 seconds
[2024-03-12T13:21:25.010+0000] {processor.py:161} INFO - Started process (PID=132) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:21:25.012+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:21:25.014+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:21:25.014+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:21:25.022+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:21:25.021+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:21:25.023+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:21:25.040+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.035 seconds
[2024-03-12T13:21:55.376+0000] {processor.py:161} INFO - Started process (PID=139) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:21:55.377+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:21:55.381+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:21:55.381+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:21:55.390+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:21:55.388+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:21:55.392+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:21:55.414+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.045 seconds
[2024-03-12T13:22:41.073+0000] {processor.py:161} INFO - Started process (PID=34) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:22:41.075+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:22:41.078+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:22:41.077+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:22:41.092+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:22:41.091+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:22:41.092+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:22:41.109+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.042 seconds
[2024-03-12T13:23:11.396+0000] {processor.py:161} INFO - Started process (PID=41) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:23:11.398+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:23:11.401+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:23:11.400+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:23:11.410+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:23:11.408+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:23:11.411+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:23:11.430+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.037 seconds
[2024-03-12T13:23:41.681+0000] {processor.py:161} INFO - Started process (PID=48) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:23:41.682+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:23:41.684+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:23:41.684+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:23:41.690+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:23:41.689+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:23:41.691+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:23:41.708+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.031 seconds
[2024-03-12T13:24:12.067+0000] {processor.py:161} INFO - Started process (PID=55) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:24:12.068+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:24:12.070+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:24:12.069+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:24:12.076+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:24:12.075+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:24:12.076+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:24:12.094+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.031 seconds
[2024-03-12T13:24:42.400+0000] {processor.py:161} INFO - Started process (PID=62) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:24:42.401+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:24:42.403+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:24:42.403+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:24:42.409+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:24:42.408+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:24:42.409+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:24:42.426+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.029 seconds
[2024-03-12T13:25:12.724+0000] {processor.py:161} INFO - Started process (PID=69) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:25:12.725+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:25:12.727+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:25:12.726+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:25:12.732+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:25:12.731+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:25:12.733+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:25:12.747+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.026 seconds
[2024-03-12T13:25:43.056+0000] {processor.py:161} INFO - Started process (PID=76) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:25:43.057+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:25:43.059+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:25:43.059+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:25:43.064+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:25:43.063+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:25:43.064+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:25:43.082+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.030 seconds
[2024-03-12T13:26:13.318+0000] {processor.py:161} INFO - Started process (PID=83) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:26:13.319+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:26:13.320+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:26:13.320+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:26:13.323+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:26:13.323+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:26:13.324+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:26:13.335+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.019 seconds
[2024-03-12T13:26:43.662+0000] {processor.py:161} INFO - Started process (PID=90) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:26:43.663+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:26:43.665+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:26:43.665+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:26:43.671+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:26:43.670+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:26:43.671+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:26:43.684+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.025 seconds
[2024-03-12T13:27:14.011+0000] {processor.py:161} INFO - Started process (PID=97) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:27:14.012+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:27:14.014+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:27:14.014+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:27:14.020+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:27:14.019+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:27:14.020+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:27:14.037+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.030 seconds
[2024-03-12T13:27:44.331+0000] {processor.py:161} INFO - Started process (PID=104) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:27:44.332+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:27:44.334+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:27:44.334+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:27:44.341+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:27:44.340+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:27:44.341+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:27:44.359+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.032 seconds
[2024-03-12T13:28:14.719+0000] {processor.py:161} INFO - Started process (PID=111) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:28:14.720+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:28:14.724+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:28:14.723+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:28:14.732+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:28:14.730+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:28:14.732+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:28:14.750+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.036 seconds
[2024-03-12T13:28:45.047+0000] {processor.py:161} INFO - Started process (PID=117) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:28:45.048+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:28:45.049+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:28:45.049+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:28:45.053+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:28:45.052+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:28:45.053+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:28:45.065+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.021 seconds
[2024-03-12T13:29:15.346+0000] {processor.py:161} INFO - Started process (PID=124) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:29:15.348+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:29:15.351+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:29:15.350+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:29:15.357+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:29:15.356+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:29:15.358+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:29:15.376+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.034 seconds
[2024-03-12T13:29:45.692+0000] {processor.py:161} INFO - Started process (PID=131) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:29:45.694+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:29:45.696+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:29:45.695+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:29:45.703+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:29:45.702+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:29:45.703+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:29:45.721+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.032 seconds
[2024-03-12T13:30:16.080+0000] {processor.py:161} INFO - Started process (PID=138) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:30:16.081+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:30:16.084+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:30:16.083+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:30:16.091+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:30:16.089+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:30:16.091+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:30:16.110+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.034 seconds
[2024-03-12T13:30:46.463+0000] {processor.py:161} INFO - Started process (PID=144) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:30:46.464+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:30:46.466+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:30:46.466+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:30:46.474+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:30:46.472+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:30:46.474+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:30:46.496+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.038 seconds
[2024-03-12T13:31:16.850+0000] {processor.py:161} INFO - Started process (PID=151) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:31:16.851+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:31:16.854+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:31:16.854+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:31:16.863+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:31:16.861+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:31:16.863+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:31:16.884+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.039 seconds
[2024-03-12T13:31:47.207+0000] {processor.py:161} INFO - Started process (PID=158) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:31:47.208+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:31:47.211+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:31:47.210+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:31:47.219+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:31:47.217+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:31:47.219+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:31:47.243+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.039 seconds
[2024-03-12T13:32:17.612+0000] {processor.py:161} INFO - Started process (PID=165) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:32:17.613+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:32:17.616+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:32:17.615+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:32:17.624+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:32:17.622+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:32:17.625+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:32:17.650+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.043 seconds
[2024-03-12T13:32:48.017+0000] {processor.py:161} INFO - Started process (PID=172) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:32:48.019+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:32:48.020+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:32:48.020+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:32:48.027+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:32:48.026+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:32:48.027+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:32:48.046+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.034 seconds
[2024-03-12T13:33:18.384+0000] {processor.py:161} INFO - Started process (PID=179) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:33:18.385+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:33:18.388+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:33:18.387+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:33:18.395+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:33:18.394+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:33:18.396+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:33:18.419+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.040 seconds
[2024-03-12T13:33:48.861+0000] {processor.py:161} INFO - Started process (PID=186) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:33:48.866+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:33:48.869+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:33:48.868+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:33:48.877+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:33:48.876+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:33:48.878+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:33:48.899+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.043 seconds
[2024-03-12T13:34:19.298+0000] {processor.py:161} INFO - Started process (PID=193) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:34:19.300+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:34:19.303+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:34:19.302+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:34:19.311+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:34:19.310+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:34:19.312+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:34:19.334+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.041 seconds
[2024-03-12T13:34:49.625+0000] {processor.py:161} INFO - Started process (PID=199) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:34:49.627+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:34:49.630+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:34:49.630+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:34:49.642+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:34:49.641+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:34:49.643+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:34:49.664+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.044 seconds
[2024-03-12T13:35:20.065+0000] {processor.py:161} INFO - Started process (PID=205) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:35:20.066+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:35:20.068+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:35:20.067+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:35:20.073+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:35:20.072+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:35:20.074+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:35:20.089+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.027 seconds
[2024-03-12T13:35:50.447+0000] {processor.py:161} INFO - Started process (PID=212) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:35:50.448+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:35:50.450+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:35:50.450+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:35:50.459+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:35:50.458+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:35:50.460+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:35:50.474+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.031 seconds
[2024-03-12T13:36:20.855+0000] {processor.py:161} INFO - Started process (PID=219) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:36:20.856+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:36:20.858+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:36:20.858+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:36:20.864+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:36:20.863+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:36:20.865+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:36:20.882+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.030 seconds
[2024-03-12T13:36:51.163+0000] {processor.py:161} INFO - Started process (PID=226) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:36:51.164+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:36:51.165+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:36:51.165+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:36:51.170+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:36:51.170+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:36:51.171+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:36:51.184+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.024 seconds
[2024-03-12T13:37:21.518+0000] {processor.py:161} INFO - Started process (PID=233) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:37:21.519+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:37:21.524+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:37:21.523+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:37:21.533+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:37:21.531+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:37:21.533+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:37:21.554+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.042 seconds
[2024-03-12T13:37:51.907+0000] {processor.py:161} INFO - Started process (PID=240) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:37:51.908+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:37:51.910+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:37:51.910+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:37:51.914+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:37:51.914+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:37:51.915+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:37:51.941+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.037 seconds
[2024-03-12T13:38:22.294+0000] {processor.py:161} INFO - Started process (PID=247) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:38:22.296+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:38:22.299+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:38:22.299+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:38:22.307+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:38:22.306+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:38:22.308+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:38:22.330+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.041 seconds
[2024-03-12T13:38:52.688+0000] {processor.py:161} INFO - Started process (PID=254) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:38:52.689+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:38:52.691+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:38:52.691+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:38:52.698+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:38:52.697+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:38:52.699+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:38:52.717+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.033 seconds
[2024-03-12T13:39:23.100+0000] {processor.py:161} INFO - Started process (PID=261) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:39:23.101+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:39:23.102+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:39:23.102+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:39:23.107+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:39:23.106+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:39:23.107+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:39:23.122+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.024 seconds
[2024-03-12T13:39:53.503+0000] {processor.py:161} INFO - Started process (PID=268) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:39:53.504+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:39:53.505+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:39:53.505+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:39:53.510+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:39:53.509+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:39:53.511+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:39:53.526+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.026 seconds
[2024-03-12T13:40:23.898+0000] {processor.py:161} INFO - Started process (PID=275) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:40:23.899+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:40:23.902+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:40:23.901+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:40:23.909+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:40:23.908+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:40:23.909+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:40:23.929+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.036 seconds
[2024-03-12T13:40:54.281+0000] {processor.py:161} INFO - Started process (PID=282) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:40:54.282+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:40:54.283+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:40:54.283+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:40:54.286+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:40:54.286+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:40:54.287+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:40:54.296+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.016 seconds
[2024-03-12T13:41:24.626+0000] {processor.py:161} INFO - Started process (PID=289) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:41:24.627+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:41:24.628+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:41:24.628+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:41:24.633+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:41:24.632+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:41:24.633+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:41:24.650+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.027 seconds
[2024-03-12T13:41:54.985+0000] {processor.py:161} INFO - Started process (PID=295) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:41:54.987+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:41:54.989+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:41:54.989+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:41:54.998+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:41:54.996+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:41:54.999+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:41:55.014+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.034 seconds
[2024-03-12T13:42:25.381+0000] {processor.py:161} INFO - Started process (PID=301) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:42:25.382+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:42:25.384+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:42:25.384+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:42:25.391+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:42:25.390+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:42:25.392+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:42:25.411+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.035 seconds
[2024-03-12T13:42:55.714+0000] {processor.py:161} INFO - Started process (PID=308) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:42:55.714+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:42:55.716+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:42:55.716+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:42:55.721+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:42:55.721+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:42:55.722+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:42:55.737+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.031 seconds
[2024-03-12T13:43:26.058+0000] {processor.py:161} INFO - Started process (PID=315) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:43:26.059+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:43:26.060+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:43:26.060+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:43:26.065+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:43:26.064+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:43:26.065+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:43:26.077+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.022 seconds
[2024-03-12T13:43:56.455+0000] {processor.py:161} INFO - Started process (PID=322) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:43:56.456+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:43:56.458+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:43:56.458+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:43:56.465+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:43:56.463+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:43:56.465+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:43:56.485+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.034 seconds
[2024-03-12T13:44:26.807+0000] {processor.py:161} INFO - Started process (PID=328) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:44:26.808+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:44:26.811+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:44:26.810+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:44:26.819+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:44:26.818+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:44:26.820+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:44:26.840+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.038 seconds
[2024-03-12T13:44:57.285+0000] {processor.py:161} INFO - Started process (PID=335) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:44:57.287+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:44:57.289+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:44:57.289+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:44:57.297+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:44:57.296+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:44:57.298+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:44:57.317+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.036 seconds
[2024-03-12T13:45:27.787+0000] {processor.py:161} INFO - Started process (PID=342) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:45:27.789+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:45:27.791+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:45:27.791+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:45:27.798+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:45:27.797+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:45:27.799+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:45:27.818+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.036 seconds
[2024-03-12T13:45:58.135+0000] {processor.py:161} INFO - Started process (PID=349) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:45:58.136+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:45:58.138+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:45:58.138+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:45:58.145+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:45:58.144+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:45:58.146+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:45:58.164+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.033 seconds
[2024-03-12T13:46:28.433+0000] {processor.py:161} INFO - Started process (PID=356) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:46:28.434+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:46:28.436+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:46:28.436+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:46:28.444+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:46:28.443+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:46:28.444+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:46:28.460+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.032 seconds
[2024-03-12T13:46:58.828+0000] {processor.py:161} INFO - Started process (PID=363) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:46:58.828+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:46:58.829+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:46:58.829+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:46:58.832+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:46:58.832+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:46:58.833+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:46:58.842+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.016 seconds
[2024-03-12T13:47:29.203+0000] {processor.py:161} INFO - Started process (PID=370) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:47:29.204+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:47:29.207+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:47:29.206+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:47:29.215+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:47:29.214+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:47:29.215+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:47:29.235+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.037 seconds
[2024-03-12T13:47:59.601+0000] {processor.py:161} INFO - Started process (PID=376) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:47:59.602+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:47:59.604+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:47:59.604+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:47:59.611+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:47:59.610+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:47:59.612+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:47:59.634+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.037 seconds
[2024-03-12T13:48:29.959+0000] {processor.py:161} INFO - Started process (PID=383) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:48:29.960+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:48:29.963+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:48:29.963+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:48:29.974+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:48:29.972+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:48:29.975+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:48:29.998+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.046 seconds
[2024-03-12T13:49:00.165+0000] {processor.py:161} INFO - Started process (PID=390) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:49:00.166+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:49:00.168+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:49:00.168+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:49:00.176+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:49:00.175+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:49:00.177+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:49:00.198+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.038 seconds
[2024-03-12T13:49:30.550+0000] {processor.py:161} INFO - Started process (PID=397) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:49:30.551+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:49:30.552+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:49:30.552+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:49:30.556+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:49:30.555+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:49:30.556+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:49:30.568+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.021 seconds
[2024-03-12T13:50:00.899+0000] {processor.py:161} INFO - Started process (PID=404) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:50:00.899+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:50:00.900+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:50:00.900+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:50:00.904+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:50:00.904+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:50:00.905+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:50:00.916+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.020 seconds
[2024-03-12T13:50:31.154+0000] {processor.py:161} INFO - Started process (PID=411) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:50:31.155+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:50:31.156+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:50:31.156+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:50:31.159+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:50:31.159+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:50:31.160+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:50:31.169+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.016 seconds
[2024-03-12T13:51:01.411+0000] {processor.py:161} INFO - Started process (PID=418) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:51:01.412+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:51:01.413+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:51:01.412+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:51:01.416+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:51:01.415+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:51:01.416+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:51:01.432+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.023 seconds
[2024-03-12T13:51:31.880+0000] {processor.py:161} INFO - Started process (PID=425) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:51:31.881+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:51:31.883+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:51:31.883+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:51:31.890+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:51:31.889+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:51:31.891+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:51:31.912+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.037 seconds
[2024-03-12T13:52:02.282+0000] {processor.py:161} INFO - Started process (PID=432) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:52:02.284+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:52:02.287+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:52:02.286+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:52:02.295+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:52:02.294+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:52:02.296+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:52:02.317+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.040 seconds
[2024-03-12T13:52:32.678+0000] {processor.py:161} INFO - Started process (PID=439) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:52:32.679+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:52:32.681+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:52:32.680+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:52:32.686+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:52:32.685+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:52:32.686+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:52:32.700+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.025 seconds
[2024-03-12T13:53:02.865+0000] {processor.py:161} INFO - Started process (PID=446) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:53:02.866+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:53:02.867+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:53:02.867+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:53:02.872+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:53:02.871+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:53:02.872+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:53:02.883+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.020 seconds
[2024-03-12T13:53:33.152+0000] {processor.py:161} INFO - Started process (PID=453) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:53:33.153+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:53:33.154+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:53:33.154+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:53:33.160+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:53:33.159+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:53:33.160+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:53:33.180+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.031 seconds
[2024-03-12T13:54:03.580+0000] {processor.py:161} INFO - Started process (PID=459) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:54:03.581+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:54:03.584+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:54:03.584+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:54:03.593+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:54:03.591+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:54:03.593+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:54:03.613+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.040 seconds
[2024-03-12T13:54:33.940+0000] {processor.py:161} INFO - Started process (PID=466) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:54:33.941+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:54:33.942+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:54:33.942+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:54:33.945+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:54:33.945+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:54:33.946+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:54:33.955+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.017 seconds
[2024-03-12T13:55:04.171+0000] {processor.py:161} INFO - Started process (PID=473) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:55:04.172+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:55:04.174+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:55:04.174+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:55:04.181+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:55:04.180+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:55:04.182+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:55:04.200+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.034 seconds
[2024-03-12T13:55:34.525+0000] {processor.py:161} INFO - Started process (PID=480) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:55:34.527+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:55:34.529+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:55:34.528+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:55:34.536+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:55:34.534+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:55:34.536+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:55:34.554+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.033 seconds
[2024-03-12T13:56:04.866+0000] {processor.py:161} INFO - Started process (PID=487) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:56:04.868+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:56:04.870+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:56:04.870+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:56:04.878+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:56:04.876+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:56:04.878+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:56:04.898+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.038 seconds
[2024-03-12T13:56:35.205+0000] {processor.py:161} INFO - Started process (PID=494) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:56:35.206+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:56:35.209+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:56:35.209+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:56:35.217+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:56:35.216+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:56:35.218+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:56:35.240+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.039 seconds
[2024-03-12T13:57:05.581+0000] {processor.py:161} INFO - Started process (PID=501) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:57:05.582+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:57:05.585+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:57:05.585+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:57:05.595+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:57:05.593+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:57:05.596+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:57:05.620+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.044 seconds
[2024-03-12T13:57:35.999+0000] {processor.py:161} INFO - Started process (PID=507) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:57:36.000+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:57:36.003+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:57:36.003+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:57:36.010+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:57:36.009+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:57:36.010+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:57:36.028+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.033 seconds
[2024-03-12T13:58:06.475+0000] {processor.py:161} INFO - Started process (PID=513) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:58:06.477+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:58:06.479+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:58:06.478+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:58:06.486+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:58:06.485+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:58:06.487+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:58:06.506+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.035 seconds
[2024-03-12T13:58:36.934+0000] {processor.py:161} INFO - Started process (PID=520) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:58:36.935+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:58:36.938+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:58:36.938+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:58:36.946+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:58:36.945+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:58:36.947+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:58:36.967+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.038 seconds
[2024-03-12T13:59:07.358+0000] {processor.py:161} INFO - Started process (PID=527) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:59:07.359+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:59:07.361+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:59:07.361+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:59:07.367+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:59:07.366+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:59:07.368+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:59:07.384+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.030 seconds
[2024-03-12T13:59:37.820+0000] {processor.py:161} INFO - Started process (PID=534) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:59:37.822+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T13:59:37.825+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:59:37.824+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:59:37.833+0000] {logging_mixin.py:188} INFO - [2024-03-12T13:59:37.832+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T13:59:37.833+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T13:59:37.855+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.040 seconds
[2024-03-12T14:00:08.162+0000] {processor.py:161} INFO - Started process (PID=541) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:00:08.163+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T14:00:08.166+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:00:08.165+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:00:08.173+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:00:08.172+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T14:00:08.173+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:00:08.192+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.034 seconds
[2024-03-12T14:00:38.586+0000] {processor.py:161} INFO - Started process (PID=548) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:00:38.588+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T14:00:38.590+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:00:38.590+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:00:38.596+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:00:38.595+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T14:00:38.597+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:00:38.616+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.035 seconds
[2024-03-12T14:01:08.889+0000] {processor.py:161} INFO - Started process (PID=554) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:01:08.890+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T14:01:08.891+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:01:08.891+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:01:08.895+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:01:08.894+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T14:01:08.895+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:01:08.906+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.019 seconds
[2024-03-12T14:01:39.128+0000] {processor.py:161} INFO - Started process (PID=561) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:01:39.129+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T14:01:39.130+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:01:39.130+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:01:39.133+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:01:39.133+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T14:01:39.134+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:01:39.144+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.018 seconds
[2024-03-12T14:02:09.510+0000] {processor.py:161} INFO - Started process (PID=567) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:02:09.511+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T14:02:09.513+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:02:09.513+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:02:09.520+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:02:09.519+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T14:02:09.521+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:02:09.540+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.034 seconds
[2024-03-12T14:02:39.913+0000] {processor.py:161} INFO - Started process (PID=580) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:02:39.915+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T14:02:39.917+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:02:39.917+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:02:39.927+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:02:39.925+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T14:02:39.927+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:02:39.939+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.030 seconds
[2024-03-12T14:03:10.247+0000] {processor.py:161} INFO - Started process (PID=587) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:03:10.247+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T14:03:10.250+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:03:10.249+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:03:10.255+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:03:10.254+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T14:03:10.256+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:03:10.272+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.028 seconds
[2024-03-12T14:03:40.602+0000] {processor.py:161} INFO - Started process (PID=594) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:03:40.603+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T14:03:40.606+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:03:40.605+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:03:40.612+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:03:40.611+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T14:03:40.613+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:03:40.626+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.028 seconds
[2024-03-12T14:04:10.961+0000] {processor.py:161} INFO - Started process (PID=601) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:04:10.962+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T14:04:10.965+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:04:10.964+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:04:10.971+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:04:10.970+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T14:04:10.972+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:04:10.991+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.034 seconds
[2024-03-12T14:04:41.295+0000] {processor.py:161} INFO - Started process (PID=608) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:04:41.297+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T14:04:41.298+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:04:41.298+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:04:41.304+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:04:41.303+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T14:04:41.305+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:04:41.319+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.027 seconds
[2024-03-12T14:05:11.668+0000] {processor.py:161} INFO - Started process (PID=614) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:05:11.669+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T14:05:11.673+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:05:11.672+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:05:11.679+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:05:11.678+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T14:05:11.680+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:05:11.696+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.032 seconds
[2024-03-12T14:05:42.070+0000] {processor.py:161} INFO - Started process (PID=621) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:05:42.071+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T14:05:42.073+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:05:42.072+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:05:42.076+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:05:42.075+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T14:05:42.077+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:05:42.088+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.020 seconds
[2024-03-12T14:06:12.403+0000] {processor.py:161} INFO - Started process (PID=627) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:06:12.404+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T14:06:12.406+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:06:12.406+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:06:12.414+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:06:12.413+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T14:06:12.415+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:06:12.435+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.037 seconds
[2024-03-12T14:06:42.654+0000] {processor.py:161} INFO - Started process (PID=633) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:06:42.654+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T14:06:42.656+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:06:42.655+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:06:42.660+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:06:42.659+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T14:06:42.660+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:06:42.671+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.020 seconds
[2024-03-12T14:07:12.971+0000] {processor.py:161} INFO - Started process (PID=640) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:07:12.972+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T14:07:12.974+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:07:12.973+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:07:12.977+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:07:12.977+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T14:07:12.978+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:07:12.988+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.020 seconds
[2024-03-12T14:07:43.335+0000] {processor.py:161} INFO - Started process (PID=647) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:07:43.336+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T14:07:43.337+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:07:43.337+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:07:43.341+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:07:43.340+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T14:07:43.341+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:07:43.353+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.020 seconds
[2024-03-12T14:08:13.766+0000] {processor.py:161} INFO - Started process (PID=653) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:08:13.768+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T14:08:13.771+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:08:13.771+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:08:13.787+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:08:13.785+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T14:08:13.787+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:08:13.808+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.049 seconds
[2024-03-12T14:08:44.143+0000] {processor.py:161} INFO - Started process (PID=660) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:08:44.144+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T14:08:44.145+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:08:44.145+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:08:44.149+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:08:44.148+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T14:08:44.149+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:08:44.160+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.018 seconds
[2024-03-12T14:09:14.482+0000] {processor.py:161} INFO - Started process (PID=666) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:09:14.483+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T14:09:14.484+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:09:14.484+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:09:14.489+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:09:14.488+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T14:09:14.491+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:09:14.506+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.026 seconds
[2024-03-12T14:09:44.757+0000] {processor.py:161} INFO - Started process (PID=673) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:09:44.757+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T14:09:44.759+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:09:44.759+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:09:44.763+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:09:44.762+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T14:09:44.763+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:09:44.774+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.020 seconds
[2024-03-12T14:10:15.004+0000] {processor.py:161} INFO - Started process (PID=680) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:10:15.005+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T14:10:15.008+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:10:15.007+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:10:15.019+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:10:15.017+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T14:10:15.019+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:10:15.090+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.090 seconds
[2024-03-12T14:10:45.184+0000] {processor.py:161} INFO - Started process (PID=687) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:10:45.185+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T14:10:45.188+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:10:45.188+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:10:45.196+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:10:45.195+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T14:10:45.197+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:10:45.218+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.037 seconds
[2024-03-12T14:11:20.413+0000] {processor.py:161} INFO - Started process (PID=33) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:11:20.417+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T14:11:20.418+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:11:20.418+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:11:20.424+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:11:20.422+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T14:11:20.425+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:11:20.445+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.035 seconds
[2024-03-12T14:11:50.690+0000] {processor.py:161} INFO - Started process (PID=40) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:11:50.691+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T14:11:50.694+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:11:50.693+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:11:50.700+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:11:50.699+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T14:11:50.700+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:11:50.713+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.026 seconds
[2024-03-12T14:12:21.052+0000] {processor.py:161} INFO - Started process (PID=47) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:12:21.053+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T14:12:21.056+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:12:21.055+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:12:21.064+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:12:21.063+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T14:12:21.065+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:12:21.084+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.037 seconds
[2024-03-12T14:19:33.546+0000] {processor.py:161} INFO - Started process (PID=99) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:19:33.547+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T14:19:33.548+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:19:33.548+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:19:33.559+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:19:33.558+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T14:19:33.559+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:19:33.578+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.037 seconds
[2024-03-12T14:20:04.006+0000] {processor.py:161} INFO - Started process (PID=106) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:20:04.008+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T14:20:04.010+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:20:04.009+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:20:04.018+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:20:04.017+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T14:20:04.019+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:20:04.040+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.037 seconds
[2024-03-12T14:20:34.466+0000] {processor.py:161} INFO - Started process (PID=114) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:20:34.467+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T14:20:34.468+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:20:34.468+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:20:34.474+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:20:34.473+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T14:20:34.474+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:20:34.486+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.023 seconds
[2024-03-12T14:21:04.873+0000] {processor.py:161} INFO - Started process (PID=121) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:21:04.874+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T14:21:04.875+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:21:04.875+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:21:04.883+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:21:04.882+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T14:21:04.884+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:21:04.906+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.037 seconds
[2024-03-12T14:21:35.217+0000] {processor.py:161} INFO - Started process (PID=127) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:21:35.218+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T14:21:35.219+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:21:35.218+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:21:35.223+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:21:35.222+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T14:21:35.223+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T14:21:35.233+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.018 seconds
[2024-03-12T15:19:23.453+0000] {processor.py:161} INFO - Started process (PID=34) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T15:19:23.454+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T15:19:23.456+0000] {logging_mixin.py:188} INFO - [2024-03-12T15:19:23.456+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T15:19:23.461+0000] {logging_mixin.py:188} INFO - [2024-03-12T15:19:23.460+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T15:19:23.461+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T15:19:23.474+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.024 seconds
[2024-03-12T15:19:53.753+0000] {processor.py:161} INFO - Started process (PID=41) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T15:19:53.754+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T15:19:53.756+0000] {logging_mixin.py:188} INFO - [2024-03-12T15:19:53.756+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T15:19:53.763+0000] {logging_mixin.py:188} INFO - [2024-03-12T15:19:53.762+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T15:19:53.763+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T15:19:53.781+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.032 seconds
[2024-03-12T15:20:23.986+0000] {processor.py:161} INFO - Started process (PID=48) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T15:20:23.987+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T15:20:23.988+0000] {logging_mixin.py:188} INFO - [2024-03-12T15:20:23.988+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T15:20:23.992+0000] {logging_mixin.py:188} INFO - [2024-03-12T15:20:23.991+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T15:20:23.992+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T15:20:24.005+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.022 seconds
[2024-03-12T15:20:54.310+0000] {processor.py:161} INFO - Started process (PID=54) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T15:20:54.311+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T15:20:54.315+0000] {logging_mixin.py:188} INFO - [2024-03-12T15:20:54.314+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T15:20:54.323+0000] {logging_mixin.py:188} INFO - [2024-03-12T15:20:54.322+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T15:20:54.324+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T15:20:54.344+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.039 seconds
[2024-03-12T15:21:24.587+0000] {processor.py:161} INFO - Started process (PID=61) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T15:21:24.588+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T15:21:24.590+0000] {logging_mixin.py:188} INFO - [2024-03-12T15:21:24.589+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T15:21:24.595+0000] {logging_mixin.py:188} INFO - [2024-03-12T15:21:24.594+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T15:21:24.596+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T15:21:24.612+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.028 seconds
[2024-03-12T15:24:08.098+0000] {processor.py:161} INFO - Started process (PID=35) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T15:24:08.099+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T15:24:08.101+0000] {logging_mixin.py:188} INFO - [2024-03-12T15:24:08.101+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T15:24:08.105+0000] {logging_mixin.py:188} INFO - [2024-03-12T15:24:08.104+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T15:24:08.106+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T15:24:08.118+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.022 seconds
[2024-03-12T15:27:40.393+0000] {processor.py:161} INFO - Started process (PID=34) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T15:27:40.397+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T15:27:40.399+0000] {logging_mixin.py:188} INFO - [2024-03-12T15:27:40.399+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T15:27:40.407+0000] {logging_mixin.py:188} INFO - [2024-03-12T15:27:40.406+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T15:27:40.407+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T15:27:40.419+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.032 seconds
[2024-03-12T15:30:58.463+0000] {processor.py:161} INFO - Started process (PID=35) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T15:30:58.464+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T15:30:58.465+0000] {logging_mixin.py:188} INFO - [2024-03-12T15:30:58.465+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T15:30:58.469+0000] {logging_mixin.py:188} INFO - [2024-03-12T15:30:58.468+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T15:30:58.469+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T15:30:58.479+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.017 seconds
[2024-03-12T15:31:28.654+0000] {processor.py:161} INFO - Started process (PID=42) to work on /opt/airflow/dags/indeed_scraper.py
[2024-03-12T15:31:28.654+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/indeed_scraper.py for tasks to queue
[2024-03-12T15:31:28.656+0000] {logging_mixin.py:188} INFO - [2024-03-12T15:31:28.655+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T15:31:28.659+0000] {logging_mixin.py:188} INFO - [2024-03-12T15:31:28.659+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T15:31:28.660+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/indeed_scraper.py
[2024-03-12T15:31:28.670+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/indeed_scraper.py took 0.019 seconds
